"""empty message

Revision ID: 378ce09312bd
Revises: cc33e1e75909
Create Date: 2024-03-02 00:56:53.282897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378ce09312bd'
down_revision = 'cc33e1e75909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('planet',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('character',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
        batch_op.drop_constraint('favorites_character_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_name_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key('favorites_planet_fkey', 'planets', ['planet'], ['id'])
        batch_op.create_foreign_key('favorites_name_fkey', 'users', ['name'], ['id'])
        batch_op.create_foreign_key('favorites_character_fkey', 'characters', ['character'], ['id'])
        batch_op.alter_column('character',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planet',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
