"""empty message

Revision ID: cc33e1e75909
Revises: 592bef1dd333
Create Date: 2024-03-02 00:54:02.337671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc33e1e75909'
down_revision = '592bef1dd333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planet'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['name'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['character'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('people_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_people_id_fkey', 'characters', ['people_id'], ['id'])
        batch_op.create_foreign_key('favorites_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favorites_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('character')
        batch_op.drop_column('planet')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
